import { existsSync, readFileSync } from 'node:fs';

import { ConditionType } from '@proton/sieve/filterModel';
import { fromSieveTree } from '@proton/sieve/fromSieveTree';
import { toSieveTree } from '@proton/sieve/toSieveTree';
import { describe, expect, it } from 'vitest';

import { REPO_FIXTURE } from './fixture-path.js';

/**
 * The first test against a real filter rather than a constructed one.
 *
 * `fixtures/recorded/filters.json` is a genuine `GET mail/v4/filters` response, captured by hand and
 * run through the scrubber. Every address, folder name and filter name in it is a pseudonym; the
 * structure is untouched, which is the part that matters here.
 *
 * It answers two questions that constructed fixtures could not, and the answers changed the plan:
 *
 *  1. **A filter can arrive with no `Simple` field.** This one did — it was authored as Sieve, so
 *     Proton returns only `Sieve` and `Tree`. The plan had assumed such filters were opaque to us
 *     and would have to be shown as "no preview possible". They are not: `Tree` is returned too,
 *     and it parses.
 *  2. **Recompiling reproduces Proton's own tree byte for byte.** That is the precondition for ever
 *     writing such a filter back. Without it, editing a Sieve-authored rule would silently rewrite
 *     parts of it — the spam preamble, the generated comments — and the only safe option would have
 *     been read-only.
 */

/**
 * The fixture is not in the repository by default.
 *
 * It is one account's real filter, pseudonymised, and it is regenerated by `pnpm spike`, which only
 * the account owner can run. Skipping is the honest behaviour for everyone else — but skipping
 * *visibly*: this test answered two questions that changed the plan, and it silently disappearing
 * would be worse than a clone that cannot run it.
 */
const FIXTURE = REPO_FIXTURE('filters.json');
const available = existsSync(FIXTURE);

interface RecordedFilter {
    Tree: unknown;
    Version: 1 | 2;
    Simple?: unknown;
    Sieve?: string;
}

/**
 * `data` is what the endpoint's own function returned, which for `getFilters` is the array itself.
 *
 * This read used to expect `data.Filters`, the shape of Proton's raw envelope. Nobody noticed,
 * because the fixture is not in the repository and the suite had never once had one to open — the
 * skip that keeps the test honest for other clones also kept it from ever being run. Reading the
 * shape defensively means the next mismatch names itself instead of arriving as a TypeError while
 * the file is still being imported, where `skipIf` cannot help.
 */
function readFilter(): RecordedFilter | undefined {
    if (!available) {
        return undefined;
    }
    const parsed = JSON.parse(readFileSync(FIXTURE, 'utf8')) as { data?: unknown };
    if (!Array.isArray(parsed.data)) {
        throw new Error(
            `${FIXTURE} hat nicht die erwartete Form: "data" muss das Array sein, das getFilters ` +
                'zurückgibt. Fixture mit `pnpm spike` neu aufnehmen.'
        );
    }
    return parsed.data[0] as RecordedFilter | undefined;
}

const filter = readFilter();

/**
 * The recorded file as it sits on disk.
 *
 * The two checks below are about the fixture as a whole, not about the one filter inside it: what
 * gets committed is the file, so the file is what has to be free of addresses.
 */
const raw = available ? readFileSync(FIXTURE, 'utf8') : '';

describe.skipIf(!available)('a real Proton filter', () => {
    it('arrives without a Simple field, but with a Tree', () => {
        expect(filter).toBeDefined();
        expect(filter?.Simple).toBeUndefined();
        expect(filter?.Sieve).toBeTypeOf('string');
        expect(Array.isArray(filter?.Tree)).toBe(true);
    });

    it('parses into the rule model despite having no Simple field', () => {
        const simple = fromSieveTree(filter?.Tree);

        expect(simple).not.toBeNull();
        expect(simple.Conditions).toHaveLength(1);
        expect(simple.Conditions[0]?.Type.value).toBe(ConditionType.SENDER);
        expect(simple.Conditions[0]?.Values.length).toBeGreaterThan(0);
        expect(simple.Actions.FileInto).toHaveLength(1);
    });

    it('recompiles to exactly the tree Proton stored', () => {
        // The precondition for editing a Sieve-authored filter at all. If this ever fails, writing
        // such a filter back would quietly change parts of it that nobody asked to change.
        const recompiled = toSieveTree(fromSieveTree(filter?.Tree), filter?.Version ?? 2);
        expect(recompiled).toEqual(filter?.Tree);
    });

    it('carries no address, anywhere', () => {
        // The fixture is committed to a repository headed for GitHub. This is the check that keeps
        // it honest as the scrubber changes.
        expect(raw).not.toMatch(/[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/);
    });

    it("keeps Proton's own generated strings readable, which is what makes it a useful fixture", () => {
        expect(raw).toContain('vnd.proton.spam-threshold');
        expect(raw).toContain('# Generated:');
        expect(raw).toContain('@comparator');
    });
});
